name: Deploy backend

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch: {}   # ← 필요 시 수동 실행

concurrency:
  group: deploy-backend-main
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/astronomy-software/byeoldori-server:latest
            ghcr.io/astronomy-software/byeoldori-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Verify files exist in Git
        run: |
          set -e
          git cat-file -e HEAD:docker-compose.prod.yml || (echo "::error::missing in repo: docker-compose.prod.yml" && exit 1)
          git cat-file -e HEAD:ops/nginx.conf         || (echo "::error::missing in repo: ops/nginx.conf" && exit 1)

      - name: Bundle deploy artifacts
        run: |
          set -e
          test -f docker-compose.prod.yml
          test -f ops/nginx.conf
          tar -czf deploy_bundle.tar.gz docker-compose.prod.yml ops/nginx.conf
          tar -tzf deploy_bundle.tar.gz 

      - name: Upload bundle
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ./deploy_bundle.tar.gz
          target: ~/byeoldori
          overwrite: true

      - name: Deploy remotely
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -Eeuo pipefail
            mkdir -p ~/byeoldori/ops
            cd ~/byeoldori
            
            tar -xzf deploy_bundle.tar.gz
            rm -f deploy_bundle.tar.gz
            
            docker compose -f docker-compose.prod.yml config -q
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            if docker compose -f docker-compose.prod.yml ps nginx >/dev/null 2>&1; then
              sleep 2
              docker compose -f docker-compose.prod.yml exec -T nginx nginx -t
              docker compose -f docker-compose.prod.yml exec -T nginx nginx -s reload || \
              docker compose -f docker-compose.prod.yml up -d --no-deps --force-recreate nginx
            fi
            
            docker image prune -af --filter "until=24h" || true
            docker compose -f docker-compose.prod.yml ps