name: Deploy backend

on:
  push:
    branches: [ "main" ]
    paths-ignore: # 문서 변경시에만 배포 미실행
      - "**/*.md"
      - "docs/**"
  workflow_dispatch: {}   # 필요 시 수동 실행

concurrency:
  group: deploy-backend-main
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/astronomy-software/byeoldori-server:latest
            ghcr.io/astronomy-software/byeoldori-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure deploy dir exists
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -Eeuo pipefail
            mkdir -p ~/byeoldori/ops

      - name: Prepare .env for server
        run: |
          printf "%s" "${{ secrets.ENV_PROD }}" > .env

      - name: Upload compose & env
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: |
            docker-compose.prod.yml
            ops/nginx.conf
            .env
          target: ~/byeoldori

      - name: Pull & restart via Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -Eeuo pipefail
            cd ~/byeoldori  
          
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker compose -f docker-compose.prod.yml exec -T nginx nginx -t
            docker compose -f docker-compose.prod.yml exec -T nginx nginx -s reload || \
            docker compose -f docker-compose.prod.yml up -d --no-deps --force-recreate nginx
            docker image prune -af --filter "until=24h" || true
            docker compose -f docker-compose.prod.yml ps