name: Deploy backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "Dockerfile"
      - "docker-compose.prod.yml"
      - "build.gradle.kts"
      - "settings.gradle.kts"
      - "src/**"
      - "ops/**"
  workflow_dispatch: {}   # ← 필요 시 수동 실행

concurrency:
  group: deploy-backend-main
  cancel-in-progress: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/astronomy-software/byeoldori-server:latest
            ghcr.io/astronomy-software/byeoldori-server:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -Eeuo pipefail
            
            cd ~/byeoldori
            
            git pull --rebase
            
            cat > .env <<'EOF'
            ${{ secrets.ENV_PROD }}
            EOF
            chmod 600 .env
            
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -af --filter "until=24h" || true
            docker compose -f docker-compose.prod.yml ps